import {describe,it,expect} from 'vitest';
import {newCollection,drawRecruit,exchangeRecruit,grantDungeonTickets,commitCollection} from '../public/english-quest/collection.js';
import {newSave,loadSave,SAVE_KEY,COLLECTION_BACKUP_KEY,sanitizeSave,persist} from '../public/english-quest/save.js';
import {validateQuestionBank,chooseBankQuestion} from '../public/english-quest/question-bank.js';
const catalog=[{id:'a_r',rarity:'R'},{id:'a_r2',rarity:'R'},{id:'a_sr',rarity:'SR'},{id:'a_ssr',rarity:'SSR'}];
const funded=()=>({...newSave(),collection:{...newCollection(),tickets:100}});
const rng=(...values)=>()=>values.shift();
const storage=(initial={})=>{const data=new Map(Object.entries(initial));return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};};
describe('earned ticket recruitment',()=>{
 it.each([[0,'R'],[.699999999,'R'],[.7,'SR'],[.94999999,'SR'],[.95,'SSR'],[.99999999,'SSR']])('rarity boundary %s gives %s',(roll,rarity)=>{expect(drawRecruit(funded(),catalog,1,rng(roll,0)).receipt.rarity).toBe(rarity);});
 it('selects both endpoints uniformly within the stable rarity pool',()=>{expect(drawRecruit(funded(),catalog,1,rng(0,0)).receipt.unitId).toBe('a_r');expect(drawRecruit(funded(),catalog,1,rng(0,.999999)).receipt.unitId).toBe('a_r2');});
 it('makes the tenth non-SR+ pull guaranteed and fortieth non-SSR pull SSR',()=>{let s=funded();for(let i=1;i<=9;i++)s=drawRecruit(s,catalog,i,rng(0,0)).state;expect(s.collection.srMisses).toBe(9);let r=drawRecruit(s,catalog,10,rng(0,0));expect(r.receipt.rarity).toBe('SR');expect(r.state.collection.srMisses).toBe(0);s=r.state;for(let i=11;i<=39;i++)s=drawRecruit(s,catalog,i,rng(0,0)).state;r=drawRecruit(s,catalog,40,rng(0,0));expect(r.receipt.guarantee).toBe('SSR');expect(r.state.collection.ssrMisses).toBe(0);});
 it('keeps 5% SSR at the SR+ guarantee boundary',()=>{const s=funded();s.collection.srMisses=9;expect(drawRecruit(s,catalog,1,rng(.95,0)).receipt.rarity).toBe('SSR');});
 it('awards duplicate shards without stats or extra ownership, and retries never reroll',()=>{const s=funded(),r=drawRecruit(s,catalog,1,rng(0,0)),again=drawRecruit(r.state,catalog,2,rng(0,0));expect(again.receipt.duplicate).toBe(true);expect(again.state.collection.shards).toBe(1);expect(again.state.roster.filter(x=>x==='a_r')).toHaveLength(1);const replay=drawRecruit(again.state,catalog,2,()=>{throw Error('Must not reroll');});expect(replay.replayed).toBe(true);expect(replay.state.collection.tickets).toBe(98);expect(s.collection.tickets).toBe(100);});
 it.each([-1,1,NaN,Infinity])('rejects invalid RNG %s before mutating',value=>{const s=funded(),before=JSON.stringify(s);expect(()=>drawRecruit(s,catalog,1,rng(value,0))).toThrow();expect(JSON.stringify(s)).toBe(before);});
 it('rejects insufficient tickets, missing rarity and stale or mismatched receipt',()=>{expect(()=>drawRecruit(newSave(),catalog,1,rng(0,0))).toThrow();expect(()=>drawRecruit(funded(),catalog.slice(0,2),1,rng(0,0))).toThrow();const r=drawRecruit(funded(),catalog,1,rng(0,0));expect(()=>drawRecruit(r.state,catalog,0,rng(0,0))).toThrow();expect(()=>exchangeRecruit(r.state,catalog,'a_sr',1)).toThrow();});
 it('redeems chosen unowned units once at the stated shard price',()=>{const s=funded();s.collection.shards=40;const r=exchangeRecruit(s,catalog,'a_sr',1);expect(r.state.collection.shards).toBe(0);expect(exchangeRecruit(r.state,catalog,'a_sr',1).replayed).toBe(true);expect(()=>exchangeRecruit(r.state,catalog,'a_sr',2)).toThrow();});
});
describe('atomic saves and rewards',()=>{
 const locks={request:async(_key,_opts,callback)=>callback()};
 it('commits ticket consumption and receipt together; retry after interruption recovers receipt',async()=>{const s=funded(),st=storage({[SAVE_KEY]:JSON.stringify(s)}),args={storage:st,key:SAVE_KEY,expectedRevision:0,sequence:1,operation:'draw',decode:x=>x,locks,mutate:x=>drawRecruit(x,catalog,1,rng(.95,0))};const r=await commitCollection(args);expect(r.state.revision).toBe(1);expect(JSON.parse(st.getItem(SAVE_KEY)).collection.tickets).toBe(99);expect((await commitCollection({...args,mutate:()=>{throw Error('Repeated');}})).replayed).toBe(true);});
 it('does not reveal a pull on storage failure and rejects conflicting revision',async()=>{const s=funded(),raw=JSON.stringify(s),st={getItem:()=>raw,setItem:()=>{throw Error('Full');}},args={storage:st,key:SAVE_KEY,expectedRevision:0,sequence:1,operation:'draw',decode:x=>x,locks,mutate:x=>drawRecruit(x,catalog,1,rng(0,0))};await expect(commitCollection(args)).rejects.toThrow('Full');await expect(commitCollection({...args,expectedRevision:1})).rejects.toThrow('another tab');expect(st.getItem()).toBe(raw);});
 it('fails closed without cross-tab locking',async()=>{await expect(commitCollection({locks:null})).rejects.toThrow('Web Locks');});
 it('awards first-clear and repeat tickets once per result, never on defeat',()=>{const s=newSave(),d={id:'test',tickets:1,firstClearTickets:2};s.battle={phase:'result',result:'victory',encounterId:'test'};expect(grantDungeonTickets(s,d).tickets).toBe(3);expect(grantDungeonTickets(s,d).tickets).toBe(3);expect(s.collection.tickets).toBe(3);s.completed.push('test');s.battle={phase:'result',result:'victory',encounterId:'test'};expect(grantDungeonTickets(s,d).tickets).toBe(1);s.battle={phase:'result',result:'defeat',encounterId:'test'};expect(grantDungeonTickets(s,d)).toBeNull();expect(s.collection.tickets).toBe(4);});
 it('backs up v1 exactly and preserves owned starters, words and settings',()=>{const old={...newSave(),version:1,roster:['hero','mage'],party:['hero','mage'],words:{strike:{o:2,n:1}},settings:{sound:false,motion:'reduced'}};delete old.collection;const raw=JSON.stringify(old),st=storage({[SAVE_KEY]:raw}),r=loadSave(st);expect(r.save.version).toBe(2);expect(st.getItem(COLLECTION_BACKUP_KEY)).toBe(raw);expect(r.save.roster).toEqual(old.roster);expect(r.save.words).toEqual(old.words);expect(r.save.collection.tickets).toBe(0);expect(loadSave(st).save).toEqual(r.save);});
 it('does not overwrite v1 when its migration backup cannot be saved',()=>{const raw=JSON.stringify({...newSave(),version:1});const st={getItem:k=>k===SAVE_KEY?raw:null,setItem:()=>{throw Error('Full');}};expect(loadSave(st).blocked).toBe(true);expect(st.getItem(SAVE_KEY)).toBe(raw);});
 it('rolls back in-memory revision on normal save failure',()=>{const s=newSave();expect(persist({setItem:()=>{throw Error();}},s)).toBe(false);expect(s.revision).toBe(0);});
 it('rejects negative economy data and preserves legal guarantee progress',()=>{const s=newSave();s.collection.tickets=-1;expect(()=>sanitizeSave(s)).toThrow();s.collection.tickets=3;s.collection.srMisses=9;s.collection.ssrMisses=39;expect(sanitizeSave(s).collection).toEqual(s.collection);});
});
const question={id:'q_0001',level:1,category:'travel',prompt:'出口を探しています。どの質問？',options:['Where is the exit?','When is dinner?','Who is singing?','Why is it cold?'],answerIndex:0,explanation:'Whereは場所を尋ねる。出口の位置を知りたい場面。',englishText:'Where is the exit?'};
describe('reviewed question ingestion',()=>{
 it('does not count unreviewed content or choice permutations',()=>{expect(validateQuestionBank([question]).count).toBe(0);expect(validateQuestionBank([question],{approvedIds:[question.id]}).count).toBe(1);const q={...question,id:'q_0002',options:[...question.options].reverse(),answerIndex:3};expect(()=>validateQuestionBank([question,q])).toThrow('duplicate question content');});
 it('keeps the correct answer attached while shuffling four choices',()=>{const bank=validateQuestionBank([question],{approvedIds:[question.id]}).approved;const q=chooseBankQuestion(bank,{}, {},()=>0);expect(q.choices).toHaveLength(4);expect(q.choices.find(c=>c.correct).text).toBe(question.options[0]);expect(chooseBankQuestion(bank,{}, {level:0},()=>0)).not.toBeNull();});
 it('rejects ambiguous choices, missing approval IDs, invalid levels and answer indexes',()=>{expect(()=>validateQuestionBank([{...question,options:['A',' A ','B','C']}])).toThrow();expect(()=>validateQuestionBank([question],{approvedIds:['q_missing']})).toThrow();expect(()=>validateQuestionBank([{...question,level:7}])).toThrow();expect(()=>validateQuestionBank([{...question,answerIndex:4}])).toThrow();});
});
