import {it,expect,vi} from 'vitest';
import {AudioManager,audioSettings,MUSIC,softenLoop} from '../public/english-quest/audio-manager.js';
import {newSave,sanitizeSave} from '../public/english-quest/save.js';
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function environment(){let contexts=0;const sources=[],gains=[];const param=()=>({value:0,setTargetAtTime:vi.fn(),setValueAtTime:vi.fn(),exponentialRampToValueAtTime:vi.fn()});class Context{constructor(){contexts++;this.state='suspended';this.currentTime=0;this.destination={};}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}close(){this.state='closed';return Promise.resolve();}createGain(){const g={gain:param(),connect(){},disconnect:vi.fn()};gains.push(g);return g;}createBufferSource(){const s={connect(){},disconnect:vi.fn(),start:vi.fn(),stop:vi.fn()};sources.push(s);return s;}createOscillator(){const o=this.createBufferSource();o.frequency=param();return o;}decodeAudioData(){return Promise.resolve({duration:152});}}const env={AudioContext:Context,fetch:vi.fn(async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(8)})),SpeechSynthesisUtterance:class{},speechSynthesis:{cancel:vi.fn(),speak:vi.fn()}};return {env,sources,gains,contexts:()=>contexts};}
it('preserves old OFF and independent bounded volume/mutes through save import',()=>{const s=newSave();s.settings={sound:false,bgmVolume:.23,seVolume:.71,bgmMuted:true,seMuted:false};expect(sanitizeSave(s).settings).toMatchObject(s.settings);expect(audioSettings({bgmVolume:8,seVolume:-1})).toMatchObject({sound:false,bgmVolume:1,seVolume:0});});
it('creates no context or requests before gesture and reuses one context for many effects',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true});expect(e.contexts()).toBe(0);expect(e.env.fetch).not.toHaveBeenCalled();await a.unlock();await flush();for(let i=0;i<3;i++){await a.unlock();await a.effect('heal');}expect(e.contexts()).toBe(1);expect(e.env.fetch).toHaveBeenCalledTimes(1);expect(e.sources.filter(s=>s.loop)).toHaveLength(1);a.dispose();});
it('switches loops without overlap and uses the battle intro only once',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true});await a.unlock();await flush();const town=a.music;a.setScene('battle');await flush();expect(town.stop).toHaveBeenCalledOnce();expect(a.music.loopStart).toBe(MUSIC.battle.loopStart);const battle=a.music;a.setScene('boss');await flush();expect(battle.stop).toHaveBeenCalledOnce();expect(a.music.loopStart).toBe(0);a.dispose();});
it('invalidates loading tracks on mute, scene switch and background pause',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true});await a.unlock();a.setScene('battle');a.setHidden(true);await flush();expect(a.music).toBeNull();expect(a.context.state).toBe('suspended');a.setHidden(false);await flush();expect(a.musicKey).toBe('battle');a.configure({sound:false});expect(a.music).toBeNull();a.dispose();});
it('ducks music through speech and restores it on late failure or cancellation',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true});await a.unlock();await flush();let failed=false;a.speak('Guard your friend.',()=>failed=true);expect(a.ducked).toBe(true);e.env.speechSynthesis.speak.mock.calls[0][0].onerror();expect(failed).toBe(true);expect(a.ducked).toBe(false);a.speak('Heal.');a.setPaused(true);expect(a.ducked).toBe(false);expect(a.music).toBeNull();a.dispose();});
it('recovers from loading/decode failure without blocking effects or the game',async()=>{const e=environment();e.env.fetch.mockRejectedValueOnce(Error('offline'));const a=new AudioManager(e.env);a.configure({sound:true});await a.unlock();await flush();expect(a.error).toBe(true);expect(await a.effect('heal')).toBe(true);await a.sync();await flush();expect(a.music).not.toBeNull();a.dispose();});
it('mute and pause prevent effects and six effect families have distinct envelopes',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true,bgmMuted:true});await a.unlock();const patterns=[];for(const k of ['slash','magic','heal','hit','victory','guard']){const before=e.sources.length;await a.effect(k);patterns.push(e.sources.slice(before).map(s=>s.frequency.setValueAtTime.mock.calls[0][0]));a.voices.clear();}expect(new Set(patterns.map(JSON.stringify)).size).toBe(6);a.configure({sound:true,seMuted:true});expect(await a.effect('heal')).toBe(false);a.dispose();});
it('joins decoded loop boundaries at zero without shortening the song',()=>{const channels=[new Float32Array(20000).fill(.5),new Float32Array(20000).fill(-.3)],buffer={sampleRate:1000,numberOfChannels:2,getChannelData:i=>channels[i]};softenLoop(buffer,7.5);for(const x of channels){expect(x).toHaveLength(20000);expect(Math.abs(x[0])).toBe(0);expect(Math.abs(x[7500])).toBe(0);expect(Math.abs(x.at(-1))).toBe(0);expect(Math.abs(x[8000])).toBeGreaterThan(0);}});
it('can resume after a page was restored with a closed context',async()=>{const e=environment(),a=new AudioManager(e.env);a.configure({sound:true,bgmMuted:true});await a.unlock();a.dispose();expect(await a.unlock()).toBe(true);expect(a.context.state).toBe('running');expect(e.contexts()).toBe(2);a.dispose();});
